## BEGIN code auto-generated by DSC 0.1.0
DSC_0314079E55 <- readRDS("dsc_result/dsc57.rds")
Y <- DSC_0314079E55$Y
control_genes <- DSC_0314079E55$control_genes
num_sv <- DSC_0314079E55$num_sv
X <- DSC_0314079E55$X
## END code auto-generated by DSC 0.1.0
ruv_ruvinv <- ruv::RUVinv(Y = Y, X = as.matrix(X[, 2]),
                        ctl = as.logical(control_genes),
                        Z = as.matrix(X[, -2]))
sebetahat <- sqrt(ruv_ruvinv$sigma2 * ruv_ruvinv$multiplier)
betahat   <- c(ruv_ruvinv$betahat)
pvalues   <- c(ruv_ruvinv$p)
df        <- rep(ruv_ruvinv$df, length = ncol(Y))
## BEGIN code auto-generated by DSC 0.1.0
saveRDS(list(betahat=betahat, sebetahat=sebetahat, df=df, pvalues=pvalues), 'dsc_result/dsc53.rds')
## END code auto-generated by DSC 0.1.0

