## BEGIN code auto-generated by DSC 0.1.0
DSC_C20F284B7F <- readRDS("dsc_result/dsc57.rds")
Y <- DSC_C20F284B7F$Y
control_genes <- DSC_C20F284B7F$control_genes
num_sv <- DSC_C20F284B7F$num_sv
X <- DSC_C20F284B7F$X
calibrate <- 1
## END code auto-generated by DSC 0.1.0
calibrate <- as.logical(calibrate)
cate_nc <- cate::cate(~Treatment, Y = Y,
                      X.data = data.frame(Treatment = X[, 2]),
                      r = num_sv, fa.method = "ml", adj.method = "nc",
                      nc = as.logical(control_genes), calibrate = calibrate)
betahat   <- c(cate_nc$beta)
sebetahat <- c(sqrt(cate_nc$beta.cov.row * cate_nc$beta.cov.col) /
    sqrt(nrow(X)))
df        <- rep(Inf, length = ncol(Y))
pvalues   <- c(cate_nc$beta.p.value)
## BEGIN code auto-generated by DSC 0.1.0
saveRDS(list(betahat=betahat, sebetahat=sebetahat, df=df, pvalues=pvalues), 'dsc_result/dsc62.rds')
## END code auto-generated by DSC 0.1.0

