## BEGIN code auto-generated by DSC 0.1.0
DSC_34A72D14D0 <- readRDS("dsc_result/dsc51.rds")
Y <- DSC_34A72D14D0$Y
control_genes <- DSC_34A72D14D0$control_genes
num_sv <- DSC_34A72D14D0$num_sv
X <- DSC_34A72D14D0$X
calibrate <- 0
## END code auto-generated by DSC 0.1.0
calibrate <- as.logical(calibrate)
cate_rr <- cate::cate(~Treatment, Y = Y,
                      X.data = data.frame(Treatment = X[, 2]),
                      r = num_sv, fa.method = "ml", adj.method = "rr",
                      calibrate = calibrate)
cate_rr_out           <- list()
betahat   <- c(cate_rr$beta)
sebetahat <- c(sqrt(cate_rr$beta.cov.row * cate_rr$beta.cov.col) / sqrt(nrow(X)))
pvalues   <- c(cate_rr$beta.p.value)
df        <- rep(Inf, length = ncol(Y))
## BEGIN code auto-generated by DSC 0.1.0
saveRDS(list(betahat=betahat, sebetahat=sebetahat, df=df, pvalues=pvalues), 'dsc_result/dsc144.rds')
## END code auto-generated by DSC 0.1.0

