## BEGIN code auto-generated by DSC 0.1.0
DSC_DA35AC37C2 <- readRDS("dsc_result/dsc51.rds")
Y <- DSC_DA35AC37C2$Y
control_genes <- DSC_DA35AC37C2$control_genes
num_sv <- DSC_DA35AC37C2$num_sv
X <- DSC_DA35AC37C2$X
## END code auto-generated by DSC 0.1.0
trash     <- capture.output(sva_out <- sva::sva(dat = t(Y), mod = X, n.sv = num_sv))
X.sv      <- cbind(X, sva_out$sv)
limma_out <- limma::lmFit(object = t(Y), design = X.sv)
betahat   <- limma_out$coefficients[, 2]
sebetahat <- limma_out$stdev.unscaled[, 2] * limma_out$sigma
df        <- limma_out$df.residual
tstats    <- betahat / sebetahat
pvalues   <- 2 * pt(-abs(tstats), df = df)
## BEGIN code auto-generated by DSC 0.1.0
saveRDS(list(betahat=betahat, sebetahat=sebetahat, df=df, pvalues=pvalues), 'dsc_result/dsc11.rds')
## END code auto-generated by DSC 0.1.0

