## BEGIN code auto-generated by DSC 0.1.0
DSC_F9EE860836 <- readRDS("dsc_result/dsc57.rds")
Y <- DSC_F9EE860836$Y
control_genes <- DSC_F9EE860836$control_genes
num_sv <- DSC_F9EE860836$num_sv
X <- DSC_F9EE860836$X
## END code auto-generated by DSC 0.1.0
## RUV4 then ASH -------------------------------------------------------
ruv_ruv4 <- ruv::RUV4(Y = Y, X = as.matrix(X[, 2]),
                      ctl = as.logical(control_genes),
                      k = num_sv, Z = as.matrix(X[, -2]))
sebetahat <- sqrt(ruv_ruv4$sigma2 * ruv_ruv4$multiplier)
betahat   <- c(ruv_ruv4$betahat)
pvalues   <- c(ruv_ruv4$p)
df        <- rep(ruv_ruv4$df, length = ncol(Y))
## BEGIN code auto-generated by DSC 0.1.0
saveRDS(list(betahat=betahat, sebetahat=sebetahat, df=df, pvalues=pvalues), 'dsc_result/dsc69.rds')
## END code auto-generated by DSC 0.1.0

