## BEGIN code auto-generated by DSC 0.1.0
DSC_9D2A0BBB64 <- readRDS("dsc_result/dsc51.rds")
Y <- DSC_9D2A0BBB64$Y
control_genes <- DSC_9D2A0BBB64$control_genes
num_sv <- DSC_9D2A0BBB64$num_sv
X <- DSC_9D2A0BBB64$X
## END code auto-generated by DSC 0.1.0
limma_out <- limma::lmFit(object = t(Y), design = X)
betahat   <- limma_out$coefficients[, 2]
sebetahat <- limma_out$stdev.unscaled[, 2] * limma_out$sigma
df        <- limma_out$df.residual
tstats    <- betahat / sebetahat
pvalues   <- 2 * pt(-abs(tstats), df = df)
## BEGIN code auto-generated by DSC 0.1.0
saveRDS(list(betahat=betahat, sebetahat=sebetahat, df=df, pvalues=pvalues), 'dsc_result/dsc52.rds')
## END code auto-generated by DSC 0.1.0

