## BEGIN code auto-generated by DSC 0.1.0
DSC_FC21F40103 <- readRDS("dsc_result/dsc51.rds")
Y <- DSC_FC21F40103$Y
control_genes <- DSC_FC21F40103$control_genes
num_sv <- DSC_FC21F40103$num_sv
X <- DSC_FC21F40103$X
## END code auto-generated by DSC 0.1.0
vout <- vicar::vruv4(Y = Y, X = X, k = num_sv, ctl = as.logical(control_genes),
                     limmashrink = TRUE, cov_of_interest = 2)
betahat   <- c(vout$betahat)
sebetahat <- c(vout$sebetahat)
pvalues   <- c(vout$pvalues)
df        <- vout$degrees_freedom
## BEGIN code auto-generated by DSC 0.1.0
saveRDS(list(betahat=betahat, sebetahat=sebetahat, df=df, pvalues=pvalues), 'dsc_result/dsc50.rds')
## END code auto-generated by DSC 0.1.0

