## BEGIN code auto-generated by DSC 0.1.0
DSC_FB1AC3E76F <- readRDS("dsc_result/dsc51.rds")
Y <- DSC_FB1AC3E76F$Y
control_genes <- DSC_FB1AC3E76F$control_genes
num_sv <- DSC_FB1AC3E76F$num_sv
X <- DSC_FB1AC3E76F$X
## END code auto-generated by DSC 0.1.0
ruv_ruv2 <- ruv::RUV2(Y = Y, X = as.matrix(X[, 2]),
                      ctl = as.logical(control_genes),
                      k = num_sv, Z = as.matrix(X[, -2]))
sebetahat <- sqrt(ruv_ruv2$sigma2 * ruv_ruv2$multiplier)
betahat   <- c(ruv_ruv2$betahat)
pvalues   <- c(ruv_ruv2$p)
df        <- rep(ruv_ruv2$df, length = ncol(Y))
## BEGIN code auto-generated by DSC 0.1.0
saveRDS(list(betahat=betahat, sebetahat=sebetahat, df=df, pvalues=pvalues), 'dsc_result/dsc115.rds')
## END code auto-generated by DSC 0.1.0

