## BEGIN code auto-generated by DSC 0.1.0
DSC_LMERGE <-
function(x, y, ...)
{
  if(length(x) == 0)
    return(y)
  if(length(y) == 0)
    return(x)
  for (i in 1:length(names(y)))
    x[names(y)[i]] = y[i]
  return(x)
}

DSC_2713B19970 <- list()
input.files <- c('dsc_result/dsc57.rds', 'dsc_result/dsc160.rds')
for (i in 1:length(input.files)) DSC_2713B19970 <- DSC_LMERGE(DSC_2713B19970, readRDS(input.files[i]))
which_null <- DSC_2713B19970$which_null
lfdr <- DSC_2713B19970$lfdr
## END code auto-generated by DSC 0.1.0
if (length(unique(which_null)) == 1) {
    auc <- NA
} else {
    auc <- pROC::roc(predictor = lfdr, response = which_null)$auc
}
score <- auc
## BEGIN code auto-generated by DSC 0.1.0
saveRDS(list(auc=auc), 'dsc_result/dsc164.rds')
## END code auto-generated by DSC 0.1.0

