## BEGIN code auto-generated by DSC 0.1.0
DSC_LMERGE <-
function(x, y, ...)
{
  if(length(x) == 0)
    return(y)
  if(length(y) == 0)
    return(x)
  for (i in 1:length(names(y)))
    x[names(y)[i]] = y[i]
  return(x)
}

DSC_2F079F4F97 <- list()
input.files <- c('dsc_result/dsc57.rds', 'dsc_result/dsc192.rds')
for (i in 1:length(input.files)) DSC_2F079F4F97 <- DSC_LMERGE(DSC_2F079F4F97, readRDS(input.files[i]))
beta_true <- DSC_2F079F4F97$beta_true
betahat <- DSC_2F079F4F97$betahat
## END code auto-generated by DSC 0.1.0
mse <- mean((betahat - beta_true) ^ 2)
score <- mse
## BEGIN code auto-generated by DSC 0.1.0
saveRDS(list(mse=mse), 'dsc_result/dsc157.rds')
## END code auto-generated by DSC 0.1.0

