## BEGIN code auto-generated by DSC 0.1.0
set.seed(1)
Nsamp <- 5
ncontrol <- 100
nullpi <- 0.9
## END code auto-generated by DSC 0.1.0
source("data_generators/datamaker_only_counts.R")
## these do not change
args_val              <- list()
args_val$log2foldsd   <- 1
args_val$tissue       <- "muscle"
args_val$path         <- "../../../data/gtex_tissue_gene_reads/"
args_val$Ngene        <- 1000
args_val$log2foldmean <- 0
args_val$skip_gene    <- 0
args_val$Nsamp        <- Nsamp
args_val$nullpi       <- nullpi
if (nullpi != 1) {
    args_val$poisthin <- TRUE
}
d_out                  <- datamaker_counts_only(args_val)
which_null             <- d_out$meta$null
control_genes          <- as.logical(which_null)
nnull                  <- sum(control_genes)
control_genes[control_genes][sample(1:nnull, size = nnull - ncontrol)] <- FALSE
beta_true              <- rep(0, length = args_val$Ngene)
if (nullpi != 1) {
    beta_true[!which_null] <- d_out$meta$true_log2foldchange
}
X                      <- as.matrix(model.matrix(~d_out$input$condition))
colnames(X)            <- c("Intercept", "Treatment")
Y                      <- t(log2(as.matrix(d_out$input$counts + 1)))
num_sv                 <- sva::num.sv(t(Y), mod = X, method = "be")
## BEGIN code auto-generated by DSC 0.1.0
saveRDS(list(Y=Y, X=X, num_sv=num_sv, which_null=which_null, beta_true=beta_true, control_genes=control_genes), 'dsc_result/dsc51.rds')
## END code auto-generated by DSC 0.1.0

