## BEGIN code auto-generated by DSC 0.1.0
DSC_3CF7EAC7B9 <- readRDS("dsc_result/dsc153.rds")
pvalues <- DSC_3CF7EAC7B9$pvalues
betahat <- DSC_3CF7EAC7B9$betahat
df <- DSC_3CF7EAC7B9$df
sebetahat <- DSC_3CF7EAC7B9$sebetahat
model <- 'ET'
## END code auto-generated by DSC 0.1.0
suppressWarnings(ashout <- ashr::ash(betahat = betahat, sebetahat = sebetahat, df = df, model = model, outputlevel = 3))
betahat <- c(ashout$PosteriorMean)
lfdr    <- c(ashout$lfdr)
pi0hat  <- c(ashr::get_pi0(ashout))
## BEGIN code auto-generated by DSC 0.1.0
saveRDS(list(betahat=betahat, lfdr=lfdr, pi0hat=pi0hat), 'dsc_result/dsc173.rds')
## END code auto-generated by DSC 0.1.0

