## BEGIN code auto-generated by DSC 0.1.0
DSC_2CE14DF46A <- readRDS("dsc_result/dsc153.rds")
pvalues <- DSC_2CE14DF46A$pvalues
betahat <- DSC_2CE14DF46A$betahat
df <- DSC_2CE14DF46A$df
sebetahat <- DSC_2CE14DF46A$sebetahat
model <- 'ET'
## END code auto-generated by DSC 0.1.0
qout    <- qvalue::qvalue(p = pvalues)
lfdr    <- c(qout$lfdr)
pi0hat  <- c(qout$pi0)
betahat <- c(betahat)
## BEGIN code auto-generated by DSC 0.1.0
saveRDS(list(betahat=betahat, lfdr=lfdr, pi0hat=pi0hat), 'dsc_result/dsc160.rds')
## END code auto-generated by DSC 0.1.0

